(deftheme 4coder-fleury "Theme from 4coder custom version from Ryan Fleury.")

(custom-theme-set-faces
 '4coder-fleury
 `(default                          ((t (:foreground "#a08563" :background "#0c0c0c"))))
 `(cursor                           ((t (:background "green"))))
 `(font-lock-keyword-face           ((t (:foreground "#f0c674"))))
 `(font-lock-operator-face          ((t (:foreground "#907553"))))
 `(font-lock-punctuation-face       ((t (:foreground "#907553"))))
 `(font-lock-bracket-face           ((t (:foreground "#907553"))))
 `(font-lock-delimiter-face         ((t (:foreground "#907553"))))
 `(font-lock-type-face              ((t (:foreground "#d8a51d"))))
 `(font-lock-constant-face          ((t (:foreground "#6b8e23"))))
 `(font-lock-variable-name-face     ((t (:foreground "#b99468"))))
 `(font-lock-builtin-face           ((t (:foreground "#DAB98F"))))
 `(font-lock-string-face            ((t (:foreground "#6b8e23"))))
 `(font-lock-comment-face           ((t (:foreground "#686868"))))
 `(font-lock-comment-delimiter-face ((t (:foreground "#686868"))))
 `(font-lock-doc-face               ((t (:foreground "#686868"))))
 `(font-lock-function-name-face     ((t (:foreground "#cc5735"))))
 `(font-lock-doc-string-face        ((t (:foreground "#6b8e23"))))
 `(font-lock-preprocessor-face      ((t (:foreground "#DAB98F"))))
 `(font-lock-warning-face           ((t (:foreground "#504038"))))
 `(region                           ((t (:background "#2f2f37"))))
 `(hl-line                          ((t (:background "#171616"))))
 `(vertico-current                  ((t (:inherit hl-line))))
 `(highlight                        ((t (:foreground nil :background "#2f2f37"))))
 `(mode-line                        ((t (:foreground "#cb9401" :background "#1f1f27"))))
 `(mode-line-inactive               ((t (:foreground "#cb9401" :background "#1f1f27"))))
 `(minibuffer-prompt                ((t (:foreground "#a08563") :bold t)))
 `(show-paren-match                 ((t (:background "#e0741b" :foreground "#000000")))))

(global-hl-line-mode +1)
(setq-default cursor-type 'bar)

