vim.api.nvim_set_hl(0, '@boolean', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, '@character', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@character.special', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, '@comment', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, '@conditional', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@constant', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, '@constant.builtin', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, '@constant.macro', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, '@constructor', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, '@debug', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, '@define', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, '@exception', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, '@field', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@float', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@function', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@function.builtin', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, '@function.macro', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@include', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, '@keyword', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@label', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.class', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.decorator', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.enum', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.enumMember', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, '@lsp.type.function', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.interface', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.macro', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.method', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.namespace', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.parameter', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@lsp.type.property', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@lsp.type.struct', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.type', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@lsp.type.variable', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@macro', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@method', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@namespace', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@number', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@operator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, '@parameter', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@preproc', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@property', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@punctuation', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, '@repeat', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@storageclass', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@string', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, '@string.escape', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, '@string.special', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, '@tag', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@text.literal', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, '@text.reference', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, '@text.title', {   fg = "#ff00ff" })
vim.api.nvim_set_hl(0, '@text.todo', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@text.underline', {   fg = "#80a0ff" })
vim.api.nvim_set_hl(0, '@text.uri', {   fg = "#80a0ff" })
vim.api.nvim_set_hl(0, '@type', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, '@type.definition', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, '@variable', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'Boolean', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'Character', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDefault', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecatedDefault', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchDefault', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzyDefault', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemKind', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindClassDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindColorDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstantDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructorDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMemberDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindEventDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindField', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFieldDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFileDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFolderDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindFunctionDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindInterfaceDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindKeywordDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindMethodDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindModuleDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindOperatorDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindPropertyDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindReferenceDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippetDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindStructDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindText', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindTextDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameterDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindUnitDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindValueDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemKindVariableDefault', {   fg = "#b300b3" })
vim.api.nvim_set_hl(0, 'CmpItemMenu', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'CmpItemMenuDefault', {   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'ColorColumn', {   bg = "#8b0000" })
vim.api.nvim_set_hl(0, 'Comment', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'Conceal', {   bg = "#4e545c",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'Conditional', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'Constant', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'Cursor', {   bg = "#e0e0e0",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'CursorColumn', {   bg = "#666666" })
vim.api.nvim_set_hl(0, 'CursorLine', {   bg = "#333842" })
vim.api.nvim_set_hl(0, 'CursorLineFold', {   bg = "#808080",   fg = "#00ffff" })
vim.api.nvim_set_hl(0, 'CursorLineNr', {   fg = "#ffff00" })
vim.api.nvim_set_hl(0, 'CursorLineSign', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsCurrentLine', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsDisabledLine', {   fg = "#424242" })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsInfo', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsLine', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIBreakpointsPath', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUICurrentFrameName', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIDecoration', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIEndofBuffer', {   fg = "#969896" })
vim.api.nvim_set_hl(0, 'DapUIFloatBorder', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIFloatNormal', {   bg = "#111317",   fg = "#fafafa" })
vim.api.nvim_set_hl(0, 'DapUIFrameName', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'DapUILineNumber', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIModifiedValue', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUINormal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'DapUIPlayPause', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIRestart', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIScope', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUISource', {   fg = "#d484ff" })
vim.api.nvim_set_hl(0, 'DapUIStepBack', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIStepInto', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIStepOut', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIStepOver', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIStop', {   fg = "#f70067" })
vim.api.nvim_set_hl(0, 'DapUIStoppedThread', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'DapUIThread', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIType', {   fg = "#d484ff" })
vim.api.nvim_set_hl(0, 'DapUIUnavailable', {   fg = "#424242" })
vim.api.nvim_set_hl(0, 'DapUIValue', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'DapUIVariable', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'DapUIWatchesEmpty', {   fg = "#f70067" })
vim.api.nvim_set_hl(0, 'DapUIWatchesError', {   fg = "#f70067" })
vim.api.nvim_set_hl(0, 'DapUIWatchesValue', {   fg = "#a9ff68" })
vim.api.nvim_set_hl(0, 'DapUIWinSelect', {   fg = "#00f1f5" })
vim.api.nvim_set_hl(0, 'Debug', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'Define', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'Delimiter', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'DevIconAi', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconAwk', {   fg = "#4d5a5e" })
vim.api.nvim_set_hl(0, 'DevIconBabelrc', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconBash', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBashProfile', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBashrc', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBat', {   fg = "#c1f12e" })
vim.api.nvim_set_hl(0, 'DevIconBazel', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBazelBuild', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBazelWorkspace', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconBinaryGLTF', {   fg = "#ffb13b" })
vim.api.nvim_set_hl(0, 'DevIconBmp', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconBrewfile', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconBzl', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconC', {   fg = "#599eff" })
vim.api.nvim_set_hl(0, 'DevIconCMake', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconCMakeLists', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconCPlusPlus', {   fg = "#f34b7d" })
vim.api.nvim_set_hl(0, 'DevIconCjs', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconClojure', {   fg = "#8dc149" })
vim.api.nvim_set_hl(0, 'DevIconClojureC', {   fg = "#8dc149" })
vim.api.nvim_set_hl(0, 'DevIconClojureDart', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconClojureJS', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconCobol', {   fg = "#005ca5" })
vim.api.nvim_set_hl(0, 'DevIconCoffee', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconConf', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconConfigRu', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconConfiguration', {   fg = "#ececec" })
vim.api.nvim_set_hl(0, 'DevIconCp', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconCpp', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconCrystal', {   fg = "#c8c8c8" })
vim.api.nvim_set_hl(0, 'DevIconCs', {   fg = "#596706" })
vim.api.nvim_set_hl(0, 'DevIconCsh', {   fg = "#4d5a5e" })
vim.api.nvim_set_hl(0, 'DevIconCson', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconCss', {   fg = "#42a5f5" })
vim.api.nvim_set_hl(0, 'DevIconCsv', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconCxx', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconD', {   fg = "#427819" })
vim.api.nvim_set_hl(0, 'DevIconDart', {   fg = "#03589c" })
vim.api.nvim_set_hl(0, 'DevIconDb', {   fg = "#dad8d8" })
vim.api.nvim_set_hl(0, 'DevIconDefault', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconDesktopEntry', {   fg = "#563d7c" })
vim.api.nvim_set_hl(0, 'DevIconDiff', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconDoc', {   fg = "#185abd" })
vim.api.nvim_set_hl(0, 'DevIconDockerfile', {   fg = "#458ee6" })
vim.api.nvim_set_hl(0, 'DevIconDocx', {   fg = "#185abd" })
vim.api.nvim_set_hl(0, 'DevIconDrools', {   fg = "#ffafaf" })
vim.api.nvim_set_hl(0, 'DevIconDropbox', {   fg = "#0061fe" })
vim.api.nvim_set_hl(0, 'DevIconDsStore', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconDump', {   fg = "#dad8d8" })
vim.api.nvim_set_hl(0, 'DevIconEdn', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconEex', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconEjs', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconElm', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconEnv', {   fg = "#faf743" })
vim.api.nvim_set_hl(0, 'DevIconEpp', {   fg = "#ffa61a" })
vim.api.nvim_set_hl(0, 'DevIconErb', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconErl', {   fg = "#b83998" })
vim.api.nvim_set_hl(0, 'DevIconEslintrc', {   fg = "#4b32c3" })
vim.api.nvim_set_hl(0, 'DevIconEx', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconExs', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconFavicon', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconFennel', {   fg = "#fff3d7" })
vim.api.nvim_set_hl(0, 'DevIconFish', {   fg = "#4d5a5e" })
vim.api.nvim_set_hl(0, 'DevIconFortran', {   fg = "#734f96" })
vim.api.nvim_set_hl(0, 'DevIconFs', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconFsharp', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconFsi', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconFsscript', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconFsx', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconGDScript', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconGemfile', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconGemspec', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconGif', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconGitAttributes', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconGitCommit', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconGitConfig', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconGitIgnore', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconGitLogo', {   fg = "#f14c28" })
vim.api.nvim_set_hl(0, 'DevIconGitModules', {   fg = "#41535b" })
vim.api.nvim_set_hl(0, 'DevIconGitlabCI', {   fg = "#e24329" })
vim.api.nvim_set_hl(0, 'DevIconGo', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconGodotProject', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconGraphQL', {   fg = "#e535ab" })
vim.api.nvim_set_hl(0, 'DevIconGruntfile', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconGulpfile', {   fg = "#cc3e44" })
vim.api.nvim_set_hl(0, 'DevIconGvimrc', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconH', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconHaml', {   fg = "#eaeae1" })
vim.api.nvim_set_hl(0, 'DevIconHbs', {   fg = "#f0772b" })
vim.api.nvim_set_hl(0, 'DevIconHeex', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconHh', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconHpp', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconHrl', {   fg = "#b83998" })
vim.api.nvim_set_hl(0, 'DevIconHs', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconHtm', {   fg = "#e34c26" })
vim.api.nvim_set_hl(0, 'DevIconHtml', {   fg = "#e44d26" })
vim.api.nvim_set_hl(0, 'DevIconHxx', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconIco', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconImportConfiguration', {   fg = "#ececec" })
vim.api.nvim_set_hl(0, 'DevIconIni', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconJava', {   fg = "#cc3e44" })
vim.api.nvim_set_hl(0, 'DevIconJavaScriptReactSpec', {   fg = "#20c2e3" })
vim.api.nvim_set_hl(0, 'DevIconJavaScriptReactTest', {   fg = "#20c2e3" })
vim.api.nvim_set_hl(0, 'DevIconJl', {   fg = "#a270ba" })
vim.api.nvim_set_hl(0, 'DevIconJpeg', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconJpg', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconJs', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconJson', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconJson5', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconJsx', {   fg = "#20c2e3" })
vim.api.nvim_set_hl(0, 'DevIconKotlin', {   fg = "#7f52ff" })
vim.api.nvim_set_hl(0, 'DevIconKotlinScript', {   fg = "#7f52ff" })
vim.api.nvim_set_hl(0, 'DevIconKsh', {   fg = "#4d5a5e" })
vim.api.nvim_set_hl(0, 'DevIconLeex', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconLess', {   fg = "#563d7c" })
vim.api.nvim_set_hl(0, 'DevIconLhs', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconLicense', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconLiquid', {   fg = "#95bf47" })
vim.api.nvim_set_hl(0, 'DevIconLock', {   fg = "#bbbbbb" })
vim.api.nvim_set_hl(0, 'DevIconLog', {   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'DevIconLua', {   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'DevIconLuau', {   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'DevIconMakefile', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconMarkdown', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconMaterial', {   fg = "#b83998" })
vim.api.nvim_set_hl(0, 'DevIconMd', {   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'DevIconMdx', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconMint', {   fg = "#87c095" })
vim.api.nvim_set_hl(0, 'DevIconMixLock', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconMjs', {   fg = "#f1e05a" })
vim.api.nvim_set_hl(0, 'DevIconMl', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconMli', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconMotoko', {   fg = "#9772fb" })
vim.api.nvim_set_hl(0, 'DevIconMustache', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconNPMIgnore', {   fg = "#e8274b" })
vim.api.nvim_set_hl(0, 'DevIconNPMrc', {   fg = "#e8274b" })
vim.api.nvim_set_hl(0, 'DevIconNim', {   fg = "#f3d400" })
vim.api.nvim_set_hl(0, 'DevIconNix', {   fg = "#7ebae4" })
vim.api.nvim_set_hl(0, 'DevIconNodeModules', {   fg = "#e8274b" })
vim.api.nvim_set_hl(0, 'DevIconOPUS', {   fg = "#f88a02" })
vim.api.nvim_set_hl(0, 'DevIconOpenTypeFont', {   fg = "#ececec" })
vim.api.nvim_set_hl(0, 'DevIconOrgMode', {   fg = "#77aa99" })
vim.api.nvim_set_hl(0, 'DevIconPackageJson', {   fg = "#e8274b" })
vim.api.nvim_set_hl(0, 'DevIconPackageLockJson', {   fg = "#7a0d21" })
vim.api.nvim_set_hl(0, 'DevIconPackedResource', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconPdf', {   fg = "#b30b00" })
vim.api.nvim_set_hl(0, 'DevIconPhp', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconPl', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconPm', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconPng', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconPp', {   fg = "#ffa61a" })
vim.api.nvim_set_hl(0, 'DevIconPpt', {   fg = "#cb4a32" })
vim.api.nvim_set_hl(0, 'DevIconPrisma', {   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'DevIconProcfile', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconProlog', {   fg = "#e4b854" })
vim.api.nvim_set_hl(0, 'DevIconPsManifestfile', {   fg = "#6975c4" })
vim.api.nvim_set_hl(0, 'DevIconPsScriptModulefile', {   fg = "#6975c4" })
vim.api.nvim_set_hl(0, 'DevIconPsScriptfile', {   fg = "#4273ca" })
vim.api.nvim_set_hl(0, 'DevIconPsb', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconPsd', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconPy', {   fg = "#ffbc03" })
vim.api.nvim_set_hl(0, 'DevIconPyc', {   fg = "#ffe291" })
vim.api.nvim_set_hl(0, 'DevIconPyd', {   fg = "#ffe291" })
vim.api.nvim_set_hl(0, 'DevIconPyo', {   fg = "#ffe291" })
vim.api.nvim_set_hl(0, 'DevIconQuery', {   fg = "#90a850" })
vim.api.nvim_set_hl(0, 'DevIconR', {   fg = "#358a5b" })
vim.api.nvim_set_hl(0, 'DevIconRake', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconRakefile', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconRb', {   fg = "#701516" })
vim.api.nvim_set_hl(0, 'DevIconReScript', {   fg = "#cc3e44" })
vim.api.nvim_set_hl(0, 'DevIconReScriptInterface', {   fg = "#f55385" })
vim.api.nvim_set_hl(0, 'DevIconRlib', {   fg = "#dea584" })
vim.api.nvim_set_hl(0, 'DevIconRmd', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconRproj', {   fg = "#358a5b" })
vim.api.nvim_set_hl(0, 'DevIconRs', {   fg = "#dea584" })
vim.api.nvim_set_hl(0, 'DevIconRss', {   fg = "#fb9d3b" })
vim.api.nvim_set_hl(0, 'DevIconSass', {   fg = "#f55385" })
vim.api.nvim_set_hl(0, 'DevIconScala', {   fg = "#cc3e44" })
vim.api.nvim_set_hl(0, 'DevIconScheme', {   fg = "#000000" })
vim.api.nvim_set_hl(0, 'DevIconScss', {   fg = "#f55385" })
vim.api.nvim_set_hl(0, 'DevIconSettingsJson', {   fg = "#854cc7" })
vim.api.nvim_set_hl(0, 'DevIconSh', {   fg = "#4d5a5e" })
vim.api.nvim_set_hl(0, 'DevIconSig', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconSlim', {   fg = "#e34c26" })
vim.api.nvim_set_hl(0, 'DevIconSln', {   fg = "#854cc7" })
vim.api.nvim_set_hl(0, 'DevIconSml', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconSolidity', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconSpecJs', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconSpecTs', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconSql', {   fg = "#dad8d8" })
vim.api.nvim_set_hl(0, 'DevIconStyl', {   fg = "#8dc149" })
vim.api.nvim_set_hl(0, 'DevIconSuo', {   fg = "#854cc7" })
vim.api.nvim_set_hl(0, 'DevIconSvelte', {   fg = "#ff3e00" })
vim.api.nvim_set_hl(0, 'DevIconSvg', {   fg = "#ffb13b" })
vim.api.nvim_set_hl(0, 'DevIconSwift', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconSystemVerilog', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconTFVars', {   fg = "#5f43e9" })
vim.api.nvim_set_hl(0, 'DevIconTcl', {   fg = "#1e5cb3" })
vim.api.nvim_set_hl(0, 'DevIconTerminal', {   fg = "#31b53e" })
vim.api.nvim_set_hl(0, 'DevIconTerraform', {   fg = "#5f43e9" })
vim.api.nvim_set_hl(0, 'DevIconTestJs', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconTestTs', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconTex', {   fg = "#3d6117" })
vim.api.nvim_set_hl(0, 'DevIconTextResource', {   fg = "#cbcb41" })
vim.api.nvim_set_hl(0, 'DevIconTextScene', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconToml', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconTor', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconTs', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconTsx', {   fg = "#1354bf" })
vim.api.nvim_set_hl(0, 'DevIconTwig', {   fg = "#8dc149" })
vim.api.nvim_set_hl(0, 'DevIconTxt', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconTypeScriptReactSpec', {   fg = "#1354bf" })
vim.api.nvim_set_hl(0, 'DevIconTypeScriptReactTest', {   fg = "#1354bf" })
vim.api.nvim_set_hl(0, 'DevIconVHDL', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconVagrantfile', {   fg = "#1563ff" })
vim.api.nvim_set_hl(0, 'DevIconVala', {   fg = "#7239b3" })
vim.api.nvim_set_hl(0, 'DevIconVerilog', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconVim', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconVimrc', {   fg = "#019833" })
vim.api.nvim_set_hl(0, 'DevIconVue', {   fg = "#8dc149" })
vim.api.nvim_set_hl(0, 'DevIconWasm', {   fg = "#5c4cdb" })
vim.api.nvim_set_hl(0, 'DevIconWebmanifest', {   fg = "#f1e05a" })
vim.api.nvim_set_hl(0, 'DevIconWebp', {   fg = "#a074c4" })
vim.api.nvim_set_hl(0, 'DevIconWebpack', {   fg = "#519aba" })
vim.api.nvim_set_hl(0, 'DevIconXcPlayground', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconXls', {   fg = "#207245" })
vim.api.nvim_set_hl(0, 'DevIconXlsx', {   fg = "#207245" })
vim.api.nvim_set_hl(0, 'DevIconXml', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconXul', {   fg = "#e37933" })
vim.api.nvim_set_hl(0, 'DevIconYaml', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconYml', {   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'DevIconZig', {   fg = "#f69a1b" })
vim.api.nvim_set_hl(0, 'DevIconZsh', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconZshenv', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconZshprofile', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconZshrc', {   fg = "#89e051" })
vim.api.nvim_set_hl(0, 'DevIconsbt', {   fg = "#cc3e44" })
vim.api.nvim_set_hl(0, 'DiagnosticError', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', {   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', {   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', {   fg = "#90ee90" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', {   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'DiagnosticHint', {   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', {   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'DiagnosticOk', {   fg = "#90ee90" })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', {   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', {   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'DiagnosticSignOk', {   fg = "#90ee90" })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', {   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', {})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', {})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', {})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', {})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', {   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', {   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', {   fg = "#90ee90" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', {   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', {   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'DiffAdd', {   bg = "#33423e" })
vim.api.nvim_set_hl(0, 'DiffChange', {   bg = "#33423e" })
vim.api.nvim_set_hl(0, 'DiffDelete', {   bg = "#24282f",   fg = "#3a404c" })
vim.api.nvim_set_hl(0, 'DiffText', {   bg = "#3e4a47" })
vim.api.nvim_set_hl(0, 'Directory', {   fg = "#e7b089" })
vim.api.nvim_set_hl(0, 'EndOfBuffer', {   fg = "#969896" })
vim.api.nvim_set_hl(0, 'Error', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'ErrorMsg', {   bg = "#ff0000",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'Exception', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, 'Float', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'FloatBorder', {   bg = "#111317",   fg = "#3e4451" })
vim.api.nvim_set_hl(0, 'FloatShadow', {   bg = "#000000" })
vim.api.nvim_set_hl(0, 'FloatShadowThrough', {   bg = "#000000" })
vim.api.nvim_set_hl(0, 'FloatTitle', {   fg = "#ff00ff" })
vim.api.nvim_set_hl(0, 'FoldColumn', {   bg = "#808080",   fg = "#00ffff" })
vim.api.nvim_set_hl(0, 'Folded', {   bg = "#4e545c",   fg = "#7c7f7c" })
vim.api.nvim_set_hl(0, 'Function', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'Identifier', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'Ignore', {   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'IncSearch', {})
vim.api.nvim_set_hl(0, 'Include', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'Keyword', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'Label', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'LineNr', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'LineNrAbove', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'LineNrBelow', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'LspInfoBorder', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'LspInfoFiletype', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'LspInfoList', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'LspInfoTip', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'LspInfoTitle', {   fg = "#ff00ff" })
vim.api.nvim_set_hl(0, 'Macro', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'MatchParen', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'ModeMsg', {})
vim.api.nvim_set_hl(0, 'MoreMsg', {   fg = "#2e8b57" })
vim.api.nvim_set_hl(0, 'MsgSeparator', {   bg = "#81a2be",   fg = "#373b41" })
vim.api.nvim_set_hl(0, 'NonText', {   fg = "#4e545c" })
vim.api.nvim_set_hl(0, 'Normal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'NormalFloat', {   bg = "#111317",   fg = "#fafafa" })
vim.api.nvim_set_hl(0, 'Number', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimAnd', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimArrow', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimAssignment', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimAssignmentWithAddition', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimAssignmentWithConcatenation', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimAssignmentWithSubtraction', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimAugmentedAssignment', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimBinaryMinus', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimBinaryOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimBinaryPlus', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimCallingParenthesis', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimColon', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimComma', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimComparison', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimComparisonModifier', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimConcat', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimConcatOrSubscript', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimContainer', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimCurly', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimDapVirtualText', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'NvimDapVirtualTextChanged', {   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'NvimDapVirtualTextError', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimDapVirtualTextInfo', {   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'NvimDict', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimDivision', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimDoubleQuote', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimDoubleQuotedBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimDoubleQuotedEscape', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimDoubleQuotedUnknownEscape', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimEnvironmentName', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimEnvironmentSigil', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'NvimFigureBrace', {   bg = "#ff0000",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'NvimFloat', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimIdentifier', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimIdentifierKey', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimIdentifierName', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimIdentifierScope', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimIdentifierScopeDelimiter', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimInternalError', {   bg = "#ff0000",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'NvimInvalid', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAnd', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidArrow', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAssignment', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithAddition', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithConcatenation', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAssignmentWithSubtraction', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidAugmentedAssignment', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidBinaryMinus', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidBinaryOperator', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidBinaryPlus', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidCallingParenthesis', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidColon', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidComma', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidComparison', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidComparisonModifier', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidConcat', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidConcatOrSubscript', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidContainer', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidCurly', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidDelimiter', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidDict', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidDivision', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuote', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedEscape', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimInvalidDoubleQuotedUnknownEscape', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentName', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidEnvironmentSigil', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidFigureBrace', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidFloat', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidIdentifier', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierKey', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierName', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScope', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidIdentifierScopeDelimiter', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidLambda', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidList', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidMod', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidMultiplication', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidNestingParenthesis', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidNot', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidNumber', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidNumberPrefix', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOperator', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOptionName', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOptionScope', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOptionScopeDelimiter', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOptionSigil', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidOr', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidParenthesis', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidPlainAssignment', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidRegister', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuote', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedQuote', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimInvalidSingleQuotedUnknownEscape', {   bg = "#ff0000",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'NvimInvalidSpacing', {   bg = "#ff0000",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NvimInvalidString', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidStringBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimInvalidStringQuote', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidStringSpecial', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimInvalidSubscript', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptBracket', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidSubscriptColon', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidTernary', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidTernaryColon', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidUnaryMinus', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidUnaryOperator', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidUnaryPlus', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimInvalidValue', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'NvimLambda', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimList', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimMod', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimMultiplication', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimNestingParenthesis', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimNot', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimNumber', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimNumberPrefix', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'NvimOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimOptionName', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimOptionScope', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimOptionScopeDelimiter', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'NvimOptionSigil', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'NvimOr', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimParenthesis', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimPlainAssignment', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimRegister', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimSingleQuote', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimSingleQuotedBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimSingleQuotedQuote', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimSingleQuotedUnknownEscape', {   bg = "#ff0000",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'NvimSpacing', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'NvimString', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimStringBody', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimStringQuote', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'NvimStringSpecial', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'NvimSubscript', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimSubscriptBracket', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimSubscriptColon', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'NvimTernary', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimTernaryColon', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimUnaryMinus', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimUnaryOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'NvimUnaryPlus', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'Operator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'Pmenu', {   bg = "#373b41",   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'PmenuExtra', {   bg = "#373b41",   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'PmenuExtraSel', {   bg = "#fbffad",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'PmenuKind', {   bg = "#373b41",   fg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'PmenuKindSel', {   bg = "#fbffad",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'PmenuSbar', {   bg = "#282c34" })
vim.api.nvim_set_hl(0, 'PmenuSel', {   bg = "#fbffad",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'PmenuThumb', {   bg = "#b4b7b4" })
vim.api.nvim_set_hl(0, 'PreCondit', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'PreProc', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'Question', {   fg = "#008000" })
vim.api.nvim_set_hl(0, 'QuickFixLine', {   bg = "#f8fe7a",   fg = "#282a2e" })
vim.api.nvim_set_hl(0, 'RedrawDebugClear', {   bg = "#ffff00" })
vim.api.nvim_set_hl(0, 'RedrawDebugComposed', {   bg = "#008000" })
vim.api.nvim_set_hl(0, 'RedrawDebugNormal', {})
vim.api.nvim_set_hl(0, 'RedrawDebugRecompose', {   bg = "#ff0000" })
vim.api.nvim_set_hl(0, 'Repeat', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'Search', {   bg = "#f8fe7a",   fg = "#282a2e" })
vim.api.nvim_set_hl(0, 'SignColumn', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'Special', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'SpecialChar', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'SpecialComment', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'SpecialKey', {   fg = "#00ffff" })
vim.api.nvim_set_hl(0, 'SpellBad', {})
vim.api.nvim_set_hl(0, 'SpellCap', {})
vim.api.nvim_set_hl(0, 'SpellLocal', {})
vim.api.nvim_set_hl(0, 'SpellRare', {})
vim.api.nvim_set_hl(0, 'Statement', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, 'StatusLine', {   bg = "#81a2be",   fg = "#373b41" })
vim.api.nvim_set_hl(0, 'StatusLineNC', {   bg = "#3f4349",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'StorageClass', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'String', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'Structure', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'Substitute', {   bg = "#f8fe7a",   fg = "#282a2e" })
vim.api.nvim_set_hl(0, 'TSPlaygroundFocus', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'TSPlaygroundLang', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'TSQueryLinterError', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'TabLine', {   bg = "#282a2e",   fg = "#5f89ad" })
vim.api.nvim_set_hl(0, 'TabLineFill', {   bg = "#969896",   fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, 'TabLineSel', {   bg = "#282a2e",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'Tag', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'TelescopeBorder', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopeMatching', {   fg = "#f2904b" })
vim.api.nvim_set_hl(0, 'TelescopeMultiIcon', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'TelescopeMultiSelection', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'TelescopeNormal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewBlock', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewCharDev', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewDate', {   fg = "#e7b089" })
vim.api.nvim_set_hl(0, 'TelescopePreviewDirectory', {   fg = "#e7b089" })
vim.api.nvim_set_hl(0, 'TelescopePreviewExecute', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'TelescopePreviewGroup', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewHyphen', {   fg = "#4e545c" })
vim.api.nvim_set_hl(0, 'TelescopePreviewLine', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'TelescopePreviewLink', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'TelescopePreviewMatch', {   bg = "#f8fe7a",   fg = "#282a2e" })
vim.api.nvim_set_hl(0, 'TelescopePreviewMessage', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewMessageFillchar', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewPipe', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewRead', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewSize', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'TelescopePreviewSocket', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, 'TelescopePreviewSticky', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePreviewUser', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopePreviewWrite', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePromptCounter', {   fg = "#4e545c" })
vim.api.nvim_set_hl(0, 'TelescopePromptNormal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopeResultsClass', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'TelescopeResultsComment', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'TelescopeResultsConstant', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffAdd', {   bg = "#33423e" })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffChange', {   bg = "#33423e" })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffDelete', {   bg = "#24282f",   fg = "#3a404c" })
vim.api.nvim_set_hl(0, 'TelescopeResultsDiffUntracked', {   fg = "#4e545c" })
vim.api.nvim_set_hl(0, 'TelescopeResultsField', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'TelescopeResultsFunction', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'TelescopeResultsIdentifier', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'TelescopeResultsLineNr', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'TelescopeResultsMethod', {})
vim.api.nvim_set_hl(0, 'TelescopeResultsNormal', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopeResultsNumber', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'TelescopeResultsOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'TelescopeResultsSpecialComment', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'TelescopeResultsStruct', {})
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TelescopeResultsVariable', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'TelescopeSelection', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'TelescopeTitle', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'TermCursor', {})
vim.api.nvim_set_hl(0, 'Title', {   fg = "#ff00ff" })
vim.api.nvim_set_hl(0, 'Todo', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'TreesitterContext', {   bg = "#111317",   fg = "#fafafa" })
vim.api.nvim_set_hl(0, 'TreesitterContextBottom', {})
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', {   bg = "#282a2e",   fg = "#969896" })
vim.api.nvim_set_hl(0, 'TreesitterContextSeparator', {   bg = "#111317",   fg = "#3e4451" })
vim.api.nvim_set_hl(0, 'Type', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'Typedef', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'Underlined', {   fg = "#80a0ff" })
vim.api.nvim_set_hl(0, 'VertSplit', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'Visual', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'WarningMsg', {   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'Whitespace', {   fg = "#8e6fbd" })
vim.api.nvim_set_hl(0, 'WildMenu', {   bg = "#ffff00",   fg = "#000000" })
vim.api.nvim_set_hl(0, 'WinBar', {})
vim.api.nvim_set_hl(0, 'WinBarNC', {})
vim.api.nvim_set_hl(0, 'WinSeparator', {   bg = "#282c34",   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'commandmode', {   bg = "#99cc99",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'diffadded', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'diffremoved', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'foldbraces', {   fg = "#f2e5bc" })
vim.api.nvim_set_hl(0, 'gitdiff', {   fg = "#c7c7c7" })
vim.api.nvim_set_hl(0, 'graphqltsproperty', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'helpdoc', {   bg = "#698b69",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'helpignore', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'htmlh1', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'insertmode', {   bg = "#f8fe7a",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'invnormal', {   bg = "#c5c8c6",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'lCursor', {   bg = "#e0e0e0",   fg = "#282c34" })
vim.api.nvim_set_hl(0, 'lspreferenceread', {   bg = "#3e4451" })
vim.api.nvim_set_hl(0, 'lspreferencewrite', {   bg = "#3e4451" })
vim.api.nvim_set_hl(0, 'luaComment', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'luaCommentDelimiter', {   fg = "#b0b1b0" })
vim.api.nvim_set_hl(0, 'luaCond', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaCondElse', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaConstant', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'luaError', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'luaFor', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaFunc', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaFunction', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'luaLabel', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'luaMetaMethod', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'luaNumber', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'luaParenError', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'luaRepeat', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'luaSpecial', {   fg = "#a3685a" })
vim.api.nvim_set_hl(0, 'luaString', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'luaString2', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'luaStringDelimiter', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'luaSymbolOperator', {   fg = "#e6b3b3" })
vim.api.nvim_set_hl(0, 'luaTable', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'luaTodo', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'luaemmyfluff', {   fg = "#ced0ce" })
vim.api.nvim_set_hl(0, 'luafunctioncall', {   fg = "#5f89ad" })
vim.api.nvim_set_hl(0, 'luakeyword', {   fg = "#d67634" })
vim.api.nvim_set_hl(0, 'lualine_a_command', {   bg = "#ff0000",   fg = "#9fa3ac" })
vim.api.nvim_set_hl(0, 'lualine_a_inactive', {   bg = "#ffff38",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_a_insert', {   bg = "#008c00",   fg = "#777b84" })
vim.api.nvim_set_hl(0, 'lualine_a_normal', {   bg = "#ffff38",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_a_replace', {   bg = "#ff0000",   fg = "#9fa3ac" })
vim.api.nvim_set_hl(0, 'lualine_a_terminal', {   bg = "#ff0000",   fg = "#9fa3ac" })
vim.api.nvim_set_hl(0, 'lualine_a_visual', {   bg = "#c400c4",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_b_command', {   bg = "#2c3039",   fg = "#ff4141" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_command', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_inactive', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_insert', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_normal', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_replace', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_terminal', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_error_visual', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_command', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_inactive', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_insert', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_normal', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_replace', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_terminal', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_hint_visual', {   bg = "#2c3039",   fg = "#d3d3d3" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_command', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_inactive', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_insert', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_normal', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_replace', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_terminal', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_info_visual', {   bg = "#2c3039",   fg = "#add8e6" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_command', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_inactive', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_insert', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_normal', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_replace', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_terminal', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diagnostics_warn_visual', {   bg = "#2c3039",   fg = "#ffa500" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_command', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_inactive', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_insert', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_normal', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_replace', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_terminal', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_added_visual', {   bg = "#2c3039",   fg = "#008000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_command', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_inactive', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_insert', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_normal', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_replace', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_terminal', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_modified_visual', {   bg = "#2c3039",   fg = "#f0e130" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_command', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_inactive', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_insert', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_normal', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_replace', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_terminal', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_diff_removed_visual', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_b_inactive', {   bg = "#2c3039",   fg = "#ffff38" })
vim.api.nvim_set_hl(0, 'lualine_b_insert', {   bg = "#2c3039",   fg = "#50dc50" })
vim.api.nvim_set_hl(0, 'lualine_b_normal', {   bg = "#2c3039",   fg = "#ffff38" })
vim.api.nvim_set_hl(0, 'lualine_b_replace', {   bg = "#2c3039",   fg = "#ff4141" })
vim.api.nvim_set_hl(0, 'lualine_b_terminal', {   bg = "#2c3039",   fg = "#ff4141" })
vim.api.nvim_set_hl(0, 'lualine_b_visual', {   bg = "#2c3039",   fg = "#c400c4" })
vim.api.nvim_set_hl(0, 'lualine_c_command', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_inactive', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_insert', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_normal', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_replace', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_terminal', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_c_visual', {   bg = "#0000ff",   fg = "#f6f6f6" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_a_command_to_lualine_b_command', {   bg = "#2c3039",   fg = "#ff0000" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_a_insert_to_lualine_b_insert', {   bg = "#2c3039",   fg = "#008c00" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_a_normal_to_lualine_b_normal', {   bg = "#2c3039",   fg = "#ffff38" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_b_command_to_lualine_c_command', {   bg = "#0000ff",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_b_insert_to_lualine_c_insert', {   bg = "#0000ff",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_transitional_lualine_b_normal_to_lualine_c_normal', {   bg = "#0000ff",   fg = "#2c3039" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_command', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_inactive', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_insert', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_normal', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_replace', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_terminal', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconDefault_visual', {   bg = "#0000ff",   fg = "#6d8086" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_command', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_inactive', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_insert', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_normal', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_replace', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_terminal', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'lualine_x_filetype_DevIconLua_visual', {   bg = "#0000ff",   fg = "#51a0cf" })
vim.api.nvim_set_hl(0, 'luametatablearithmetic', {   fg = "#8e6fbd" })
vim.api.nvim_set_hl(0, 'luametatableequivalence', {   fg = "#8e6fbd" })
vim.api.nvim_set_hl(0, 'luametatableevents', {   fg = "#8e6fbd" })
vim.api.nvim_set_hl(0, 'luamykeyword', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'luaspecialfunctions', {   fg = "#a3bbd0" })
vim.api.nvim_set_hl(0, 'luastatement', {   fg = "#f6fe47" })
vim.api.nvim_set_hl(0, 'markdownh1', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'markdownh2', {   fg = "#a3bbd0" })
vim.api.nvim_set_hl(0, 'markdownh3', {   fg = "#c5d4e1" })
vim.api.nvim_set_hl(0, 'mkdlinebreak', {})
vim.api.nvim_set_hl(0, 'normalmode', {   bg = "#cc6666",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'nvimmap', {   fg = "#698b69" })
vim.api.nvim_set_hl(0, 'pythonbuiltinfunc', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'pythonbytes', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'pythonbytescontent', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'pythonbyteserror', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'pythonbytesescape', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'pythonbytesescapeerror', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'pythonnone', {   fg = "#d98c8c" })
vim.api.nvim_set_hl(0, 'pythonoperator', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'pythonrawbytes', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'pythonself', {   fg = "#c9b3cf" })
vim.api.nvim_set_hl(0, 'pythonselfarg', {   fg = "#969896" })
vim.api.nvim_set_hl(0, 'qffilename', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'replacemode', {   bg = "#f8fe7a",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'semshifree', {})
vim.api.nvim_set_hl(0, 'semshiimported', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'semshilocal', {})
vim.api.nvim_set_hl(0, 'semshiselected', {   bg = "#3e4451" })
vim.api.nvim_set_hl(0, 'semshiself', {   fg = "#c9b3cf" })
vim.api.nvim_set_hl(0, 'signifysignadd', {   fg = "#99cc99" })
vim.api.nvim_set_hl(0, 'signifysignchange', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'signifysigndelete', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'sqlkeyword', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'startifybracket', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'startifyfile', {   fg = "#c04040" })
vim.api.nvim_set_hl(0, 'startifyfooter', {   fg = "#373b41" })
vim.api.nvim_set_hl(0, 'startifyheader', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'startifynumber', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'startifypath', {   fg = "#77bb77" })
vim.api.nvim_set_hl(0, 'startifysection', {   fg = "#fbffad" })
vim.api.nvim_set_hl(0, 'startifyslash', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'startifyspecial', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'terminalmode', {   bg = "#698b69",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'tsconstant', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'tsfunction', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'tsgenerics', {   fg = "#5f89ad" })
vim.api.nvim_set_hl(0, 'tsinclude', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'tsvariable', {   fg = "#e0e0e0" })
vim.api.nvim_set_hl(0, 'tsvariablebuiltin', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'tsxclosecomponentname', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'tsxclosetag', {   fg = "#e7b089" })
vim.api.nvim_set_hl(0, 'tsxclosetagname', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'tsxcomponentname', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'tsxelseoperator', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'tsxtag', {   fg = "#e7b089" })
vim.api.nvim_set_hl(0, 'tsxtagname', {   fg = "#de935f" })
vim.api.nvim_set_hl(0, 'tsxtypes', {   fg = "#a3bbd0" })
vim.api.nvim_set_hl(0, 'typescriptbraces', {   fg = "#5f89ad" })
vim.api.nvim_set_hl(0, 'typescriptdecorators', {   fg = "#77bb77" })
vim.api.nvim_set_hl(0, 'typescriptendcolons', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'typescriptstorageclass', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'typescripttype', {   fg = "#b294bb" })
vim.api.nvim_set_hl(0, 'user1', {   bg = "#f8fe7a",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'user2', {   bg = "#cc6666",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'user3', {   bg = "#99cc99",   fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'vimautoloadfunction', {   fg = "#f3fe14" })
vim.api.nvim_set_hl(0, 'vimbracket', {   fg = "#96535c" })
vim.api.nvim_set_hl(0, 'vimcommand', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'vimcommenttitle', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'vimfunction', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'vimfuncvar', {   fg = "#8e6fbd" })
vim.api.nvim_set_hl(0, 'vimiscommand', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'vimlet', {   fg = "#aa92cd" })
vim.api.nvim_set_hl(0, 'vimmap', {   fg = "#698b69" })
vim.api.nvim_set_hl(0, 'vimmaplhs', {   fg = "#f8fe7a" })
vim.api.nvim_set_hl(0, 'vimmapmodkey', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'vimnotation', {   fg = "#8abeb7" })
vim.api.nvim_set_hl(0, 'vimnotfunc', {   fg = "#81a2be" })
vim.api.nvim_set_hl(0, 'vimwikibold', {   fg = "#cc6666" })
vim.api.nvim_set_hl(0, 'visuallinemode', {   bg = "#38556d" })
vim.api.nvim_set_hl(0, 'visualmode', {   bg = "#38556d" })
